import { useState, useRef } from 'react';
import { useNavigate } from 'react-router-dom';
import DOMPurify from 'dompurify';
import { useAppDispatch } from '../store';
import { query, createPage } from '../api';
import type { Page } from '../types';
import { Button } from './ui/Button';
import { Card } from './ui/Card';
import { Textarea } from './ui/Textarea';

// Simple markdown renderer (no external deps)
function renderMarkdown(text: string): string {
  return text
    // Headings
    .replace(/^### (.+)$/gm, '<h3 class="text-base font-semibold text-text-primary mt-4 mb-1">$1</h3>')
    .replace(/^## (.+)$/gm, '<h2 class="text-lg font-semibold text-text-primary mt-5 mb-2">$1</h2>')
    .replace(/^# (.+)$/gm, '<h1 class="text-xl font-bold text-text-primary mt-6 mb-2">$1</h1>')
    // Bold + italic
    .replace(/\*\*\*(.+?)\*\*\*/g, '<strong><em>$1</em></strong>')
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    // Inline code
    .replace(/`([^`]+)`/g, '<code class="px-1 py-0.5 rounded text-xs font-mono" style="background:#2a2a3a;color:#cba6f7">$1</code>')
    // Code blocks
    .replace(/```[\w]*\n([\s\S]*?)```/g, '<pre class="my-3 p-3 rounded overflow-x-auto text-xs font-mono" style="background:#2a2a3a;color:#cdd6f4"><code>$1</code></pre>')
    // Blockquotes
    .replace(/^> (.+)$/gm, '<blockquote class="border-l-2 pl-3 my-2 text-text-secondary italic" style="border-color:#4B91F1">$1</blockquote>')
    // Unordered lists
    .replace(/^[-*] (.+)$/gm, '<li class="ml-4 list-disc text-text-secondary">$1</li>')
    // Ordered lists
    .replace(/^\d+\. (.+)$/gm, '<li class="ml-4 list-decimal text-text-secondary">$1</li>')
    // Links
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, '<a href="$2" class="text-accent hover:underline" target="_blank" rel="noopener">$1</a>')
    // Horizontal rule
    .replace(/^---$/gm, '<hr class="my-4" style="border-color:#3a3a4a">')
    // Paragraphs (double newline)
    .replace(/\n\n/g, '</p><p class="mb-3 text-text-secondary leading-relaxed">')
    // Wrap in paragraph
    .replace(/^(?!<)(.+)$/gm, (line) =>
      line.startsWith('<') ? line : line,
    );
}

export default function QueryPanel() {
  const dispatch = useAppDispatch();
  const navigate = useNavigate();
  const [question, setQuestion] = useState('');
  const [answer, setAnswer] = useState('');
  const [citations, setCitations] = useState<Page[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [saving, setSaving] = useState(false);
  const [savedSlug, setSavedSlug] = useState<string | null>(null);
  const answerRef = useRef('');

  async function handleSubmit(e: React.FormEvent) {
    e.preventDefault();
    if (!question.trim() || loading) return;

    setAnswer('');
    setCitations([]);
    setError(null);
    setSavedSlug(null);
    answerRef.current = '';
    setLoading(true);

    try {
      await query(
        question.trim(),
        (token) => {
          answerRef.current += token;
          setAnswer(answerRef.current);
        },
        (pages) => {
          setCitations(pages);
        },
      );
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setLoading(false);
    }
  }

  async function handleSaveAsPage() {
    if (!answer || saving) return;
    setSaving(true);
    try {
      const titleLine = question.trim().slice(0, 80);
      const content = `# ${titleLine}\n\n> *Generated by Archivum AI*\n\n${answer}\n\n---\n\n**Sources:**\n${citations.map((c) => `- [[${c.slug}|${c.title}]]`).join('\n')}`;

      const page = await createPage({ title: titleLine, content });
      dispatch({ type: 'UPSERT_PAGE', page });
      setSavedSlug(page.slug);
    } catch (err) {
      setError((err as Error).message);
    } finally {
      setSaving(false);
    }
  }

  return (
    <div className="flex flex-col h-full bg-bg">
      {/* Input area */}
      <div
        className="shrink-0 border-b border-border p-4 bg-panel/40 backdrop-blur supports-[backdrop-filter]:bg-panel/30"
      >
        <h2 className="text-sm font-semibold text-muted-foreground mb-3 uppercase tracking-wider">
          Ask your knowledge base
        </h2>
        <form onSubmit={handleSubmit} className="flex gap-2">
          <Textarea
            value={question}
            onChange={(e) => setQuestion(e.target.value)}
            placeholder="Ask a question about your notes..."
            rows={3}
            onKeyDown={(e) => {
              if (e.key === 'Enter' && (e.ctrlKey || e.metaKey)) {
                e.preventDefault();
                handleSubmit(e);
              }
            }}
            className="flex-1 resize-none min-h-[88px]"
          />
          <Button
            type="submit"
            variant="primary"
            disabled={loading || !question.trim()}
            className="self-end"
          >
            {loading ? 'Querying...' : 'Ask'}
          </Button>
        </form>
        <p className="text-xs text-muted-foreground mt-1">Ctrl+Enter to submit</p>
      </div>

      {/* Answer area */}
      <div className="flex-1 overflow-y-auto p-4">
        {error && (
          <div className="rounded-lg p-3 mb-4 text-sm text-red-300 border border-red-400/25 bg-red-500/10">
            {error}
          </div>
        )}

        {loading && !answer && (
          <div className="space-y-2">
            <div className="skeleton h-4 w-full" />
            <div className="skeleton h-4 w-5/6" />
            <div className="skeleton h-4 w-4/5" />
          </div>
        )}

        {answer && (
          <div className="max-w-3xl">
            {/* Streaming indicator */}
            {loading && (
              <div className="flex items-center gap-2 mb-3">
                <span className="inline-block w-2 h-2 rounded-full bg-accent animate-pulse" />
                <span className="text-xs text-muted-foreground">Generating...</span>
              </div>
            )}

            {/* Answer content */}
            <div
              className="prose-custom text-text-secondary leading-relaxed"
              dangerouslySetInnerHTML={{
                __html: DOMPurify.sanitize(
                  `<p class="mb-3 text-text-secondary leading-relaxed">${renderMarkdown(answer)}</p>`,
                  {
                    ALLOWED_ATTR: ['class', 'style', 'href', 'target', 'rel'],
                  },
                ),
              }}
            />

            {/* Actions */}
            {!loading && (
              <div className="mt-6 pt-4 border-t border-border flex items-center gap-3">
                {savedSlug ? (
                  <button
                    onClick={() => navigate(`/wiki/${savedSlug}`)}
                    className="text-sm text-accent hover:underline"
                  >
                    View saved page →
                  </button>
                ) : (
                  <Button
                    onClick={handleSaveAsPage}
                    disabled={saving}
                    variant="secondary"
                    size="sm"
                  >
                    {saving ? 'Saving...' : 'Save as page'}
                  </Button>
                )}
              </div>
            )}

            {/* Citations */}
            {citations.length > 0 && (
              <div
                className="mt-6 pt-4 border-t border-border"
              >
                <h3 className="text-xs font-semibold text-muted-foreground uppercase tracking-wider mb-3">
                  Sources
                </h3>
                <div className="space-y-1">
                  {citations.map((page) => (
                    <button
                      key={page.slug}
                      onClick={() => navigate(`/wiki/${page.slug}`)}
                      className="block text-left w-full text-sm text-accent hover:underline"
                    >
                      {page.title}
                    </button>
                  ))}
                </div>
              </div>
            )}
          </div>
        )}

        {!loading && !answer && !error && (
          <div className="flex items-center justify-center h-full">
            <Card className="max-w-sm p-4">
              <p className="text-muted-foreground text-sm">
                Ask anything about your knowledge base. Archivum will search your notes and generate a contextual answer.
              </p>
            </Card>
          </div>
        )}
      </div>
    </div>
  );
}
